api = "0.7"

[buildpack]
    homepage = "https://github.com/willsather/pnpm-buildpack"
    id = "willsather/pnpm"
    name = "PNPM"
    version = "0.0.1"

    [[buildpack.licenses]]
        type = "MIT"

[metadata]
    include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
    pre-package = "./scripts/build.sh"

    [metadata.default_versions]
        pnpm = "8.*"

    [[metadata.dependencies]]
        checksum = "sha256:78d245def692cbcee56c35c9385c0858b88a2ebc23c1e23fbf47273da3c39586"
        id = "pnpm"
        name = "pnpm"
        version = "8.15.4"
        uri = "https://github.com/pnpm/pnpm/releases/download/v8.15.4/pnpm-linux-x64"
        purl = "pkg:generic/pnpm@v8.15.4?checksum=ae56ef2bd37599237ed4e7aef284fa449cacc150fd4d3081c43f969d2b3b6a2f&download_url=https://github.com/pnpm/pnpm/archive/refs/tags/v8.15.4.tar.gz"
        source = "https://github.com/pnpm/pnpm/archive/refs/tags/v8.15.4.tar.gz"
        source-checksum = "sha256:ae56ef2bd37599237ed4e7aef284fa449cacc150fd4d3081c43f969d2b3b6a2f"
        stacks = ["io.buildpacks.stacks.jammy", "*"]

[[stacks]]
    id = "*"