api = "0.7"

[buildpack]
    homepage = "https://github.com/willsather/pnpm-buildpack"
    id = "willsather/pnpm-start"
    name = "PNPM Start"
    version = "0.0.1"

    [[buildpack.licenses]]
        type = "MIT"

[metadata]
    include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
    pre-package = "./scripts/build.sh"

[[stacks]]
    id = "*"
